### PR TITLE
RFC for new CQT & model setups

### PR DESCRIPTION
**Pull request by cjacoby**
Root = C0, 7 octaves (6 octaves only gives you ~1kHz).

First pass at CQT & WCQT model for Experiment 1.

Comments requested on these changes. (no merge yet)

---
This change is [Reviewable](https://reviewable.io/reviews/ejhumphrey/harmonic-cnn/36)

### CODE REVIEW

**Comment by bmcfee** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[hcnn/train/models.py, line 23 \[r1\]](https://reviewable.io:443/reviews/ejhumphrey/harmonic-cnn/36#-KR52mL7MGy0cC32BGh6:-KR52mL7MGy0cC32BGh7:b-7bsl3i) ([raw file](https://github.com/ejhumphrey/harmonic-cnn/blob/643722ee2878852309ac97b4eb1337df3ad9a4dc/hcnn/train/models.py#L23)):*
> ```Python
> WCQT_DIMS = (7, 54)
> HCQT_DIMS = (3, 252)
> ```

CQT_DIMS doesn't match CQT_PARAMS above.  Maybe source directly from there?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ejhumphrey/harmonic-cnn/36)*

**Comment by cjacoby** [comment]
Okay, @bmcfee  - here are new model definitions based on the discussion over in #25. Please review and let me know what you think; where possible, I've tried to include my math in the comments.

Currently, it seems like for the MF model, we would need to double the number of filters to keep everything else within the same ballpark parameter-wise.

(Extracting features right now; will kick off some of these models in the AM once you've OK'd this.)

**Comment by bmcfee** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[hcnn/train/models.py, line 22 \[r2\]](https://reviewable.io:443/reviews/ejhumphrey/harmonic-cnn/36#-KR9-FgXDyF21Pw27IDG:-KR9-FgXDyF21Pw27IDH:b-3gt3rb) ([raw file](https://github.com/ejhumphrey/harmonic-cnn/blob/f5e3b4a815d8d6f6f1ba4bbbba9c874a64a6aab6/hcnn/train/models.py#L22)):*
> ```Python
> BINS_PER_OCTAVE = 36
> CQT_DIMS = 252
> WCQT_DIMS = (CQT_DIMS / BINS_PER_OCTAVE, BINS_PER_OCTAVE * 1.5)
> ```

integer math here please :grin: 

---

*[hcnn/train/models.py, line 584 \[r2\]](https://reviewable.io:443/reviews/ejhumphrey/harmonic-cnn/36#-KR9006YIdfl5gBdgtPH:-KR9006ZPE4xwqBM7dg3:b7ob96a) ([raw file](https://github.com/ejhumphrey/harmonic-cnn/blob/f5e3b4a815d8d6f6f1ba4bbbba9c874a64a6aab6/hcnn/train/models.py#L584)):*
> ```Python
>     """Model definition for M2: small 2-d CQT filters
>     """
>     L1_FILTER = (7, 7 * 3)
> ```

this *3 ought to draw from the HCQT_DIMS tuple, but it's fine for now.

---

*[hcnn/train/streams.py, line 158 \[r2\]](https://reviewable.io:443/reviews/ejhumphrey/harmonic-cnn/36#-KR90fj3PIfVN0ykQQHZ:-KR90fj3PIfVN0ykQQH_:bglj9vq) ([raw file](https://github.com/ejhumphrey/harmonic-cnn/blob/f5e3b4a815d8d6f6f1ba4bbbba9c874a64a6aab6/hcnn/train/streams.py#L158)):*
> ```Python
> 
>         # Get the frame means, and remove the lowest 1/4
>         cqt_mu = cqt[0, :num_obs].mean(axis=1)
> ```

do you still want to do this on cqt instead of wcqt?  not 100% following the code this minute (still absorbing caffeine), so if this is intentional, please disregard my comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ejhumphrey/harmonic-cnn/36)*

**Comment by bmcfee** [comment]
Two minor comments and one question-mark, but I think we're generally looking good here.

---

Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ejhumphrey/harmonic-cnn/36#-:-KR91-keS9po5aDO568y:blm6lug)*

**Comment by cjacoby** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[hcnn/train/models.py, line 23 \[r1\]](https://reviewable.io:443/reviews/ejhumphrey/harmonic-cnn/36#-KR52mL7MGy0cC32BGh6:-KR9jhziS6t2gzKtY2l8:b-g6s9c) ([raw file](https://github.com/ejhumphrey/harmonic-cnn/blob/643722ee2878852309ac97b4eb1337df3ad9a4dc/hcnn/train/models.py#L23)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> CQT_DIMS doesn't match CQT_PARAMS above.  Maybe source directly from there?
</details>
Okay, I updated these all to pull directly from the CQT defs.

---

*[hcnn/train/models.py, line 22 \[r2\]](https://reviewable.io:443/reviews/ejhumphrey/harmonic-cnn/36#-KR9-FgXDyF21Pw27IDG:-KR9iWZSE51avHzfRlO9:b-dgblag) ([raw file](https://github.com/ejhumphrey/harmonic-cnn/blob/f5e3b4a815d8d6f6f1ba4bbbba9c874a64a6aab6/hcnn/train/models.py#L22)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> integer math here please :grin: 
</details>
This is psudo hold-over from some @ejhumphrey code for WCQT's before; It used to be 24 bins per octave for the CQT, and 36 bins for the WCQT, to include an octave and a half. 

...can I just cast it to an int / round / whatever?

---

*[hcnn/train/streams.py, line 158 \[r2\]](https://reviewable.io:443/reviews/ejhumphrey/harmonic-cnn/36#-KR90fj3PIfVN0ykQQHZ:-KR9k6E_76e0zl4xhT8E:b-i3ej5l) ([raw file](https://github.com/ejhumphrey/harmonic-cnn/blob/f5e3b4a815d8d6f6f1ba4bbbba9c874a64a6aab6/hcnn/train/streams.py#L158)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> do you still want to do this on cqt instead of wcqt?  not 100% following the code this minute (still absorbing caffeine), so if this is intentional, please disregard my comment.
</details>
There's some cruft here based on previous assumptions about sampling files that I need to fix now.

(We were sampling windows of length 8 from whole files, instead of now just returning the full 1s of the file.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ejhumphrey/harmonic-cnn/36)*

**Comment by bmcfee** [comment]
Reviewed 1 of 2 files at r3.
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[hcnn/train/models.py, line 22 \[r2\]](https://reviewable.io:443/reviews/ejhumphrey/harmonic-cnn/36#-KR9-FgXDyF21Pw27IDG:-KR9lakDzBU0Do8bTlWu:bd9xtrk) ([raw file](https://github.com/ejhumphrey/harmonic-cnn/blob/f5e3b4a815d8d6f6f1ba4bbbba9c874a64a6aab6/hcnn/train/models.py#L22)):*
<details><summary><i>Previously, cjacoby (Christopher Jacoby) wrote…</i></summary>
> This is psudo hold-over from some @ejhumphrey code for WCQT's before; It used to be 24 bins per octave for the CQT, and 36 bins for the WCQT, to include an octave and a half. 
> 
> ...can I just cast it to an int / round / whatever?
</details>
I'd replace it by
```python
WCQT_DIMS = (CQT_DIMS // BINS_PER_OCTAVE, (BINS_PER_OCTAVE * 2) // 3)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ejhumphrey/harmonic-cnn/36)*

**Comment by cjacoby** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[hcnn/train/models.py, line 22 \[r2\]](https://reviewable.io:443/reviews/ejhumphrey/harmonic-cnn/36#-KR9-FgXDyF21Pw27IDG:-KR9mtHVDK9NHrxIf7WH:b32v57) ([raw file](https://github.com/ejhumphrey/harmonic-cnn/blob/f5e3b4a815d8d6f6f1ba4bbbba9c874a64a6aab6/hcnn/train/models.py#L22)):*
<details><summary><i>Previously, bmcfee (Brian McFee) wrote…</i></summary>
> I'd replace it by
> ```python
> WCQT_DIMS = (CQT_DIMS // BINS_PER_OCTAVE, (BINS_PER_OCTAVE * 2) // 3)
> ```
</details>
+1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ejhumphrey/harmonic-cnn/36)*

**Comment by cjacoby** [comment]
I'm gonna merge it now so i can move on to fixing the streamer.

**Pull request merged**
